# https://taskfile.dev

version: '3'

tasks:
  build:
    dotenv:
      - ".env"
    env:
      CGO_ENABLED: 0
      GOTRACEBACK: "crash"
    cmds:
      - echo "YANDEX CLIENT ${YANDEX_CLIENT_ID}"
      - echo "YANDEX SECRET ${YANDEX_CLIENT_SECRET}"
      - |
        go build -o ./bin/yandex_tui \
          -ldflags "-X github.com/nifle3/yandex_music_tui/internal/yandexApi.—ÅlientId=${YANDEX_CLIENT_ID} \
                    -X github.com/nifle3/yandex_music_tui/internal/yandexApi.clientSecret=${YANDEX_CLIENT_SECRET}" \
          ./cmd/yandexMusicTui
    silent: true

  run:
    cmds:
      - ./bin/yandex_tui
    silent: true
