# https://taskfile.dev

version: '3'

tasks:
  build:
    dotenv:
      - ".env.build"
    env:
      CGO_ENABLED: 0
      GOTRACEBACK: "crash"
    cmds:
      - echo "Version ${VERSION}"
      - |
        go build -o ./bin/yandex_tui \
          -ldflags "-X main.Version=${VERSION}" \
          ./cmd/tui
    silent: true

  run:
    cmds:
      - "./bin/yandex_tui --yandex_oauth={{.YANDEX_OAUTH}}"
    vars:
      YANDEX_OAUTH: ""
    silent: true

  test:
    cmds:
      - "go test ./..."
    silent: true
